import type { NextConfig } from "next";

// All packages in the react-markdown / unified / micromark / hast ecosystem
// ship as ESM-only. Next.js (webpack) can't import them as CommonJS at runtime,
// so we tell Next.js to transpile them into the bundle instead.
const esmPackages = [
  "react-markdown",
  "remark-parse",
  "remark-rehype",
  "unified",
  "bail",
  "trough",
  "vfile",
  "vfile-message",
  "is-plain-obj",
  "devlop",
  "hast-util-to-jsx-runtime",
  "hast-util-whitespace",
  "html-url-attributes",
  "property-information",
  "space-separated-tokens",
  "comma-separated-tokens",
  "decode-named-character-reference",
  "character-entities",
  "character-entities-html4",
  "character-entities-legacy",
  "character-reference-invalid",
  "ccount",
  "mdast-util-from-markdown",
  "mdast-util-to-hast",
  "mdast-util-to-markdown",
  "mdast-util-to-string",
  "mdast-util-phrasing",
  "mdast-util-mdx-expression",
  "mdast-util-mdx-jsx",
  "mdast-util-mdxjs-esm",
  "micromark",
  "micromark-core-commonmark",
  "micromark-factory-destination",
  "micromark-factory-label",
  "micromark-factory-space",
  "micromark-factory-title",
  "micromark-factory-whitespace",
  "micromark-util-character",
  "micromark-util-chunked",
  "micromark-util-classify-character",
  "micromark-util-combine-extensions",
  "micromark-util-decode-numeric-character-reference",
  "micromark-util-decode-string",
  "micromark-util-encode",
  "micromark-util-html-tag-name",
  "micromark-util-normalize-identifier",
  "micromark-util-resolve-all",
  "micromark-util-sanitize-uri",
  "micromark-util-subtokenize",
  "micromark-util-symbol",
  "micromark-util-types",
  "unist-util-is",
  "unist-util-position",
  "unist-util-stringify-position",
  "unist-util-visit",
  "unist-util-visit-parents",
  "estree-util-is-identifier-name",
  "parse-entities",
  "stringify-entities",
  "trim-lines",
  "zwitch",
  "longest-streak",
  "is-alphabetical",
  "is-alphanumerical",
  "is-decimal",
  "is-hexadecimal",
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  transpilePackages: esmPackages,
};

export default nextConfig;
